#
# KOA REST API BOILERPLATE
#
# build:
#   docker build --force-rm -t posquit0/koa-rest-api-boilerplate .
#   docker build --force-rm -t kakakhang/e-contract .
# run:
#   docker run --rm --it --env-file=path/to/.env --name koa-rest-api-boilerplate -p 80:7071 posquit0/koa-rest-api-boilerplate
#
#

FROM node:18.17.1-alpine as build

# Set the working directory
WORKDIR /usr/local/app

# Install all the dependencies
RUN npm install -g yarn --force

# Add the source code to app
COPY ./ /usr/local/app/

RUN rm -rf /usr/local/app/node_modules

RUN yarn install --network-timeout 1000000
# Generate the build of the application
RUN yarn run build-testing

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx-testing/ /etc/nginx/conf.d

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist/ /usr/share/nginx/html

EXPOSE 8080
