export const SET_STATE = 'SET_STATE'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR'
export const MARK_READ_NOTIFICATION = 'MARK_READ_NOTIFICATION'
export const TOGGLE_NAVBAR_GROUP_ITEMS = 'TOGGLE_NAVBAR_GROUP_ITEMS'
export const ACTIVE_NAVBAR_GROUP = 'ACTIVE_NAVBAR_GROUP'
export const DELETE_TAG = 'DELETE_TAG'
export const DELETE_GROUP = 'DELETE_GROUP'
export const CREATE_TAG = 'CREATE_TAG'
export const CREATE_GROUP = 'CREATE_GROUP'
export const UPDATE_TAG = 'UPDATE_TAG'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const GET_TAGS = 'GET_TAGS'
export const GET_USERS = 'GET_USERS'
export const GET_GROUPS = 'GET_GROUPS'
export default {
  SET_STATE,
  TOGGLE_NAVBAR,
  HIDE_SIDEBAR,
  GET_NOTIFICATIONS,
  MARK_READ_NOTIFICATION,
  ACTIVE_NAVBAR_GROUP,
  TOGGLE_NAVBAR_GROUP_ITEMS,
  GET_TAGS,
  UPDATE_TAG,
  CREATE_TAG,
  DELETE_TAG,
  GET_USERS,
  CREATE_GROUP,
  UPDATE_GROUP,
  GET_GROUPS,
  DELETE_GROUP
}
